apiVersion: v1
kind: Service
metadata:
   name: flask-app
spec:
   type: ClusterIP
   selector:
      app: flask-app
   ports:
   - protocol: TCP
     port: 5000
     targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
    name: flask-app
    labels:
       app: flask-app
spec:
    containers:
    - name: flask-app
      image: mks1011/task2-app:latest # Dockerhub
      ports:
        - containerPort: 5000
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: supersecret-password

---          
apiVersion: v1
kind: Service
metadata:
   name: mysql
spec:
   type: ClusterIP
   selector:
      app: mysql
   ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306
---
apiVersion: v1
kind: Pod
metadata:
    name: mysql
    labels:
       app: mysql
spec:
    containers:
    - name: mysql
      image: mks1011/task2-db:latest # Dockerhub
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: supersecret-password
